---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
#   when: ansible_distribution == "Ubuntu" and  ansible_distribution_version == "8.2"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install httpd package
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: add php support for httpd
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"
